---
sudo: required

language: python
python:
  - 3.6
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

branches:
  only:
    - unreviewed
    - unreviewed2
    - devel
    - test_devel
    - PLAT-113-add-travis-integration

env:
  global:
    - secure: "ggFd85OvBLN8ZxZHCqd6/hcNKXuICxyt1bdya9CAjmcyq2/p3bDe/Tbwdk3WOgg/jAcOuCy1iXbtHgNgpdLIOSt9UVZHTpv7TtE5cooAGMA6zKptnaKiYaIGwrMza2Ja62qWSXOet8V1fQqIHOgZiH/3MkS9cZzZjguYJdtp0IftktAJuoXi9W8HsKNSOCdT15A/wxPXJiw/cmHANvaQL8SMT62NCKPtOR4f1boS/jbZ01Ky0UwVAytZc9og8MOtoEnSfDtE4iwZ4T+zkNNTruo74xX6Sw3AWm36hLB4mJJutFhqVtVN3/dp6k8OSz1M8h1n1bZbQTnQPrztNEtlwtcXnBi4hn/3JPTB6KyimP/zIoYVhK0fKj//ohAc9yLgZHq5mqCEM1suzJxwX7Se2XxLb1UiwCJ9JO4mwvMaH0OhgN34GAFnnXpVSAfxN/GPmW2sYMJwkbsv+CvetyzItnuObwEYST7meoikGVt70zV3v0I8qdzIjAtnfDpZs8AjZCy9l6r8vdPhhxTqIoJZcCQWoaMMKKHVccygZYUNaO8EMXa++M/3KSgAJ43w6UQiqSb+QSyhFvjZT7rOWlqxJsKC1J9pblgOEtCke6snsSbI8dy0I1l4jQrX3j+41uc7KUyGhMRKFJ9wO+QeLIF9mKTAKCB/BgmNPRwGUdnnRlo="
    - secure: "TYHGDZFIcpP1W/UBt/oeVMNxqQ9hw1WzKDSNIkkuXldFFSkvOqOlR49ZaqGrfxohEdePx0P8wtxAEANX7XcettZyJ3LDE48De+0B4jIClByuTS4UECjnSh7g3L54JwP74dW2vl9Yn+WjAbAkTuVvZ+5UfifCx9MSqpD+vvbfJTx3XXGEVXOcpMTyqD4acrcwz6R9V7yFieS/7wyAFhUD+Jkr2ZLEiv9q/3PtdEgsCoQuXhV6SxQNplJzc0TuVGZvjEoWyDsUTGs1HRXfA7FQ7wpEK6QRqCZDsdOxygWgHdn1hvR6u4OezFMas+V9dQjM+J+ibfMf0FPyF1GQmkuEJPVPIrG3HjqaB+20eTYh8qhvgKaZIn783bb6F+rVMvBfovVxZpsYghV/DZk+VrBuiLRGsBBz85TvTCk2U0Llzb/VzDwA0GU6lqzHYwNVu/UtprHexhIPaMNyVXOxdW68OBzEP62y7DxZn21xy4Q0F8zP6aLyhluhVmi1cScN3GxpmxlLsCNCS0I0LoqdaNF1bWTWm1XlZzAv5a3yD/EWBlmBwhzIWxhglLsAWlHUk1KJF3kx5xfQDTwYxcFO3NhPzgla/QfH9ecOTO86uW+DgmSp40Y96SnISn3wUn/AFZHV1vOh2comrWJWhwG06S/nAN9IGJXMpZXSVjSc/D/XgSA="

before_script:
  - sudo add-apt-repository ppa:ansible/ansible -y
  - sudo apt-get update
  - sudo apt-get install python3-pip shellcheck ansible
  - ansible --version
  - pip3 install -r dev-requirements.txt
  - sudo pip2 install -r dev-requirements.txt
  - "./lint-all-the-files.sh"
  - "echo success"
  - "true"

script:
  - "cp aws_credentials.shippable_template aws_credentials.yml"
  - "ansible-playbook -vvvvv test-system.yml -i localhost,"
  - "behave"
